In [2]:
import numpy as np

# Question 1


In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr+2

array([3, 4, 5, 6, 7])

In [ ]:
arr*3

array([ 3,  6,  9, 12, 15])

In [ ]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5])

# Question 2

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])

In [ ]:
arr[::-1]

array([5, 4, 6, 3, 2, 1])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
def most_frequent_value_and_indices(arr):
    unique, counts = np.unique(arr, return_counts=True)
    most_frequent = unique[np.argmax(counts)]
    indices = np.where(arr == most_frequent)[0]
    return most_frequent, indices
most_frequent_value_and_indices(x)
most_frequent_value_and_indices(y)

(1, array([0, 1, 2]))

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.size

10

In [ ]:
counts = np.bincount(x)
a=np.argmax(counts)
print("most frequent element is",a)
for i in range(len(x)):
  if x[i]==a:
    print(i)

most frequent element is 1
0
5
7
8
9


In [ ]:
counts = np.bincount(y)
a=np.argmax(counts)

print("most frequent element is",a)
for i in range(len(y)):
  if y[i]==a:
    print(i)

most frequent element is 1
0
1
2


#Question 3


In [ ]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [ ]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr[0,2]

30

In [ ]:
arr[2,0]

70

# Question 4

In [ ]:
yash=np.array(np.linspace(10,100,25))

In [ ]:
yash

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [ ]:
yash.shape

(25,)

In [ ]:
yash.ndim

1

In [ ]:
yash.size

25

In [ ]:
yash.dtype

dtype('float64')

In [ ]:
yash.itemsize*yash.size

200

In [ ]:
yash.reshape(25,1)

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

In [ ]:
yash

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [ ]:
k=yash.T

In [ ]:
k

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

# Question 5

In [ ]:
u=[1,0]
v=[0,1]
z=[]
for n, m in zip(u, v):
    z.append(n+m)
z

[1, 1]

In [1]:
ucs420_yash=[[10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]]

In [3]:
ucs420_yash=np.array(ucs420_yash)

In [5]:
mean=ucs420_yash.mean()
mean

43.333333333333336

In [6]:
median=np.median(ucs420_yash)
median

37.5

In [7]:
maxi=np.max(ucs420_yash)
maxi

90

In [8]:
mini=np.min(ucs420_yash)
mini

10

In [9]:
uni=np.unique(ucs420_yash)
uni

array([10, 15, 20, 30, 35, 40, 50, 60, 70, 80, 90])

In [12]:
reshaped_ucs420_yash=np.reshape(ucs420_yash,(4,3))
reshaped_ucs420_yash

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

In [14]:
resized_ucs420_yash=np.resize(ucs420_yash,(2,3))
resized_ucs420_yash

array([[10, 20, 30],
       [40, 50, 60]])